Change (docker): Combine nginx and php to a single image for both `ASP` with env var support for configuration
In <= v3.2.0, `asp` had separate `nginx` and `php` images.

Now: `asp` image containing both `nginx` and `php`, with environment variable support, and entrypoint that sets the correct permissions.

Benefits:

- Easier to deploy / upgrade. No need to separate `nginx` and `php` containers
- Environment variable configuration means no more need to mount config into `asp` container
- Entrypoint script sets permissions on volumes. `init-container` should only need to set permissions for `db` volume

Notable changes:
- Add documentation for upgrading docker images to v3.3.x from prior versions
- Update `./docs/examples`
- Add tests for production builds for examples in `./docs/examples`

Closes #69

diff --git a/.github/workflows/ci-master-pr.yml b/.github/workflows/ci-master-pr.yml
--- a/.github/workflows/ci-master-pr.yml
+++ b/.github/workflows/ci-master-pr.yml
@@ -16,31 +16,23 @@ jobs:
       matrix:
         testenv:
           - dev
+          - prod
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
       uses: actions/checkout@v3
 
-    - name: Set up Docker Buildx
-      id: buildx
-      uses: docker/setup-buildx-action@v2
+    # This is commented out, so we use the default 'docker' driver instead of the 'docker-container' driver. When using 'docker-container' driver, there appears to be a rate limit on writes on Github CI which causes buildx to fail with error code 17 when it is exporting to cache
+    # - name: Set up Docker Buildx
+    #   id: buildx
+    #   uses: docker/setup-buildx-action@v2
 
-    - name: Cache Docker layers (nginx)
+    - name: Cache Docker layers
       uses: actions/cache@v3
       with:
-        path: /tmp/.buildx-cache-nginx
-        key: ${{ runner.os }}-buildx-nginx-${{ github.sha }}
+        path: /tmp/.buildx-asp-cache-nginx
+        key: ${{ runner.os }}-buildx-asp-${{ github.sha }}
         restore-keys: |
-          ${{ runner.os }}-buildx-nginx-
-          ${{ runner.os }}-buildx-
-
-    - name: Cache Docker layers (php)
-      uses: actions/cache@v3
-      with:
-        path: /tmp/.buildx-cache-php
-        key: ${{ runner.os }}-buildx-php-${{ github.sha }}
-        restore-keys: |
-          ${{ runner.os }}-buildx-php-
           ${{ runner.os }}-buildx-
 
     - name: Print buildx and compose
@@ -54,14 +46,21 @@ jobs:
       run: |
         set -eux
         docker compose -f docker-compose.yml -f docker-compose.build.yml up --build -d
-        docker compose -f docker-compose.test.yml up
+        docker compose -f docker-compose.test.yml --profile dev up
+
+    - name: Integration test 1 (prod)
+      if: matrix.testenv == 'prod'
+      run: |
+        set -eux
+        (
+            cd docs/full-bf2-stack-example
+            sed -i '$!N;s@ports:\n      - 53:53.*@@;P;D' docker-compose.yml    # Remove coredns ports because it conflicts with system-resolved on the host
+            docker compose -f docker-compose.yml -f docker-compose.build.prod.yml up --build -d
+        )
+        docker compose -f docker-compose.test.yml --profile prod up
+        docker compose -f docker-compose.test.yml --profile dns up
 
   build:
-    strategy:
-      matrix:
-        variant:
-          - nginx
-          - php
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
@@ -91,10 +90,9 @@ jobs:
     - name: Cache Docker layers
       uses: actions/cache@v3
       with:
-        path: /tmp/.buildx-cache-${{ matrix.variant }}
-        key: ${{ runner.os }}-buildx-${{ matrix.variant }}-${{ github.sha }}
+        path: /tmp/.buildx-cache-asp
+        key: ${{ runner.os }}-buildx-${{ github.sha }}
         restore-keys: |
-          ${{ runner.os }}-buildx-${{ matrix.variant }}-
           ${{ runner.os }}-buildx-
 
     # This step generates the docker tags
@@ -108,12 +106,12 @@ jobs:
         # type=ref,event=branch generates tag(s) on branch only. E.g. 'master-<variant>', 'master-abc0123-<variant>'
         # type=ref,event=tag generates tag(s) on tags only. E.g. 'v0.0.0-<variant>', 'v0.0.0-abc0123-<variant>'
         tags: |
-          type=ref,suffix=-${{ matrix.variant }},event=pr
-          type=ref,suffix=-{{sha}}-${{ matrix.variant }},event=pr
-          type=ref,suffix=-${{ matrix.variant }},event=branch
-          type=ref,suffix=-{{sha}}-${{ matrix.variant }},event=branch
-          type=ref,suffix=-${{ matrix.variant }},event=tag
-          type=ref,suffix=-{{sha}}-${{ matrix.variant }},event=tag
+          type=ref,suffix=,event=pr
+          type=ref,suffix=-{{sha}},event=pr
+          type=ref,suffix=,event=branch
+          type=ref,suffix=-{{sha}},event=branch
+          type=ref,suffix=,event=tag
+          type=ref,suffix=-{{sha}},event=tag
         # Disable 'latest' tag
         flavor: |
           latest=false
@@ -131,36 +129,36 @@ jobs:
       if: github.event_name == 'pull_request'
       uses: docker/build-push-action@v3
       with:
-        file: Dockerfile.${{ matrix.variant }}
+        file: Dockerfile
         context: '.'
         target: prod
         platforms: linux/amd64
         push: false
         tags: ${{ steps.meta.outputs.tags }}
-        cache-from: type=local,src=/tmp/.buildx-cache-${{ matrix.variant }}
-        cache-to: type=local,dest=/tmp/.buildx-cache-${{ matrix.variant }}-new,mode=max
+        cache-from: type=local,src=/tmp/.buildx-cache-asp
+        cache-to: type=local,dest=/tmp/.buildx-cache-asp-new,mode=max
 
     - name: Build and push
       # Run on master and tags
       if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
       uses: docker/build-push-action@v3
       with:
-        file: Dockerfile.${{ matrix.variant }}
+        file: Dockerfile
         context: '.'
         target: prod
         platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/s390x
         push: true
         tags: ${{ steps.meta.outputs.tags }}
-        cache-from: type=local,src=/tmp/.buildx-cache-${{ matrix.variant }}
-        cache-to: type=local,dest=/tmp/.buildx-cache-${{ matrix.variant }}-new,mode=max
+        cache-from: type=local,src=/tmp/.buildx-cache-asp
+        cache-to: type=local,dest=/tmp/.buildx-cache-asp-new,mode=max
 
     # Temp fix
     # https://github.com/docker/build-push-action/issues/252
     # https://github.com/moby/buildkit/issues/1896
     - name: Move cache
       run: |
-        rm -rf /tmp/.buildx-cache-${{ matrix.variant }}
-        mv /tmp/.buildx-cache-${{ matrix.variant }}-new /tmp/.buildx-cache-${{ matrix.variant }}
+        rm -rf /tmp/.buildx-cache-asp
+        mv /tmp/.buildx-cache-asp-new /tmp/.buildx-cache-asp
 
   update-draft-release:
     needs: [test, build]
diff --git a/docker-compose.test.yml b/docker-compose.test.yml
--- a/docker-compose.test.yml
+++ b/docker-compose.test.yml
@@ -1,41 +1,14 @@
 version: '2.2'
 services:
-  test-routes:
+  test-ready:
+    profiles:
+      - dev
+      - prod
+      - dns
     image: alpine:latest
-    environment:
-      URLS: |
-        http://asp-nginx/ 403
-        http://asp-nginx/.htaccess 401
-        http://asp-nginx/ASP/ 200
-        http://asp-nginx/ASP/aspx 401
-        http://asp-nginx/ASP/bf2statistics.php 403
-        http://asp-nginx/ASP/frontend 401
-        http://asp-nginx/ASP/frontend/css/bootstrap.min.css 200
-        http://asp-nginx/ASP/frontend/images/maps/foo.png 200
-        http://asp-nginx/ASP/frontend/images/ranks/foo.png 200
-        http://asp-nginx/ASP/frontend/images/armies/foo.png 200
-        http://asp-nginx/ASP/frontend/css/bootstrap.min.css 200
-        http://asp-nginx/ASP/createplayer.aspx 200
-        http://asp-nginx/ASP/getawardsinfo.aspx 200
-        http://asp-nginx/ASP/getbackendinfo.aspx 200
-        http://asp-nginx/ASP/getleaderboard.aspx 200
-        http://asp-nginx/ASP/getmapinfo.aspx 200
-        http://asp-nginx/ASP/getplayerid.aspx 200
-        http://asp-nginx/ASP/getplayerinfo.aspx 200
-        http://asp-nginx/ASP/getrankinfo.aspx 200
-        http://asp-nginx/ASP/getunlocksinfo.aspx 200
-        http://asp-nginx/ASP/ranknotification.aspx 200
-        http://asp-nginx/ASP/searchforplayers.aspx 200
-        http://asp-nginx/ASP/selectunlock.aspx 200
-        http://asp-nginx/ASP/verifyplayer.aspx 200
-        http://asp-nginx/ASP/index.php 200
-        http://asp-nginx/ASP/ranknotification.aspx 200
-        http://asp-nginx/ASP/searchforplayers.aspx 200
-        http://asp-nginx/ASP/selectunlock.aspx 200
-        http://asp-nginx/ASP/getplayerinfo.aspx 200
-        http://asp-nginx/ASP/system 401
     networks:
       - bf2-network
+    stop_signal: SIGKILL
     entrypoint:
       - /bin/sh
     command:
@@ -46,10 +19,10 @@ services:
           echo "Waiting for stack to be ready"
           s=0
           while true; do
-              nc -vz -w 1 asp-nginx 80 \
-                  && nc -vz -w 1 asp-php 9000 \
-                  && nc -vz -w 1 db 3306 \
-                  && break || true
+              nc -vz -w 1 asp 80 \
+                && nc -vz -w 1 asp 9000 \
+                && nc -vz -w 1 db 3306 \
+                && break || true
               s=$$(( $$s + 1 ))
               if [ "$$s" -eq 600 ]; then
                   exit 1
@@ -58,6 +31,57 @@ services:
               sleep 3
           done
 
+  test-routes:
+    profiles:
+      - dev
+      - prod
+    image: alpine:latest
+    environment:
+      URLS: |
+        http://asp/ 403
+        http://asp/.htaccess 401
+        http://asp/ASP/ 200
+        http://asp/ASP/aspx 401
+        http://asp/ASP/bf2statistics.php 403
+        http://asp/ASP/frontend 401
+        http://asp/ASP/frontend/css/bootstrap.min.css 200
+        http://asp/ASP/frontend/images/maps/foo.png 200
+        http://asp/ASP/frontend/images/ranks/foo.png 200
+        http://asp/ASP/frontend/images/armies/foo.png 200
+        http://asp/ASP/frontend/css/bootstrap.min.css 200
+        http://asp/ASP/createplayer.aspx 200
+        http://asp/ASP/getawardsinfo.aspx 200
+        http://asp/ASP/getbackendinfo.aspx 200
+        http://asp/ASP/getleaderboard.aspx 200
+        http://asp/ASP/getmapinfo.aspx 200
+        http://asp/ASP/getplayerid.aspx 200
+        http://asp/ASP/getplayerinfo.aspx 200
+        http://asp/ASP/getrankinfo.aspx 200
+        http://asp/ASP/getunlocksinfo.aspx 200
+        http://asp/ASP/ranknotification.aspx 200
+        http://asp/ASP/searchforplayers.aspx 200
+        http://asp/ASP/selectunlock.aspx 200
+        http://asp/ASP/verifyplayer.aspx 200
+        http://asp/ASP/index.php 200
+        http://asp/ASP/ranknotification.aspx 200
+        http://asp/ASP/searchforplayers.aspx 200
+        http://asp/ASP/selectunlock.aspx 200
+        http://asp/ASP/getplayerinfo.aspx 200
+        http://asp/ASP/system 401
+
+        http://phpmyadmin/ 200
+    networks:
+      - bf2-network
+    depends_on:
+      test-ready:
+        condition: service_completed_successfully
+    stop_signal: SIGKILL
+    entrypoint:
+      - /bin/sh
+    command:
+      - -c
+      - |
+          set -eu
           echo "$$URLS" | awk NF | while read -r i j; do
               if wget -q -SO- "$$i" 2>&1 | grep "HTTP/1.1 $$j " > /dev/null; then
                   echo "PASS: $$i"
@@ -67,6 +91,139 @@ services:
               fi
           done
 
+  test-endpoints:
+    profiles:
+      - prod
+    image: alpine:latest
+    environment:
+      ENDPOINTS: |
+        asp.example.com/ 403
+        asp.example.com/.htaccess 401
+        asp.example.com/ASP/ 200
+        asp.example.com/ASP/aspx 401
+        asp.example.com/ASP/bf2statistics.php 403
+        asp.example.com/ASP/frontend 401
+        asp.example.com/ASP/frontend/css/bootstrap.min.css 200
+        asp.example.com/ASP/frontend/images/maps/foo.png 200
+        asp.example.com/ASP/frontend/images/ranks/foo.png 200
+        asp.example.com/ASP/frontend/images/armies/foo.png 200
+        asp.example.com/ASP/frontend/css/bootstrap.min.css 200
+        asp.example.com/ASP/createplayer.aspx 200
+        asp.example.com/ASP/getawardsinfo.aspx 200
+        asp.example.com/ASP/getbackendinfo.aspx 200
+        asp.example.com/ASP/getleaderboard.aspx 200
+        asp.example.com/ASP/getmapinfo.aspx 200
+        asp.example.com/ASP/getplayerid.aspx 200
+        asp.example.com/ASP/getplayerinfo.aspx 200
+        asp.example.com/ASP/getrankinfo.aspx 200
+        asp.example.com/ASP/getunlocksinfo.aspx 200
+        asp.example.com/ASP/ranknotification.aspx 200
+        asp.example.com/ASP/searchforplayers.aspx 200
+        asp.example.com/ASP/selectunlock.aspx 200
+        asp.example.com/ASP/verifyplayer.aspx 200
+        asp.example.com/ASP/index.php 200
+        asp.example.com/ASP/ranknotification.aspx 200
+        asp.example.com/ASP/searchforplayers.aspx 200
+        asp.example.com/ASP/selectunlock.aspx 200
+        asp.example.com/ASP/getplayerinfo.aspx 200
+        asp.example.com/ASP/system 401
+    network_mode: host
+    depends_on:
+      test-ready:
+        condition: service_completed_successfully
+    stop_signal: SIGKILL
+    entrypoint:
+      - /bin/sh
+    command:
+      - -c
+      - |
+          set -eu
+          apk add --no-cache curl
+          echo "$$ENDPOINTS" | awk NF | while read -r i j; do
+              d=$$( echo "$$i" | cut -d '/' -f1 )
+              if curl --head -skL http://$$i --resolve $$d:80:127.0.0.1 --resolve $$d:443:127.0.0.1 2>&1 | grep -E "^HTTP/(1.1|2) $$j " > /dev/null; then
+                  echo "PASS: $$i"
+              else
+                  echo "FAIL: $$i"
+                  exit 1
+              fi
+          done
+
+  test-interal-dns:
+    profiles:
+      - dns
+    image: alpine:latest
+    environment:
+      DNS: |
+        battlefield2.available.gamespy.com
+        battlefield2.master.gamespy.com
+        battlefield2.ms14.gamespy.com
+        master.gamespy.com
+        motd.gamespy.com
+        gpsp.gamespy.com
+        gpcm.gamespy.com
+        gamespy.com
+        bf2web.gamespy.com
+        gamestats.gamespy.com
+        eapusher.dice.se
+    networks:
+      - bf2-network
+    depends_on:
+      test-ready:
+        condition: service_completed_successfully
+    stop_signal: SIGKILL
+    entrypoint:
+      - /bin/sh
+    command:
+      - -c
+      - |
+          set -eu
+          echo "$$DNS" | awk NF | grep -v '127.0.0' | while read -r h; do
+              if nslookup $$h | grep -v '127.0.0' | grep -E '^Address: [0-9\.]+$$'; then
+                  echo "PASS: $$h"
+              else
+                  echo "FAIL: $$h"
+                  exit 1
+              fi
+          done
+
+  test-coredns:
+    profiles:
+      - dns
+    image: alpine:latest
+    environment:
+      DNS: |
+        192.168.1.100 battlefield2.available.gamespy.com
+        192.168.1.100 battlefield2.master.gamespy.com
+        192.168.1.100 battlefield2.ms14.gamespy.com
+        192.168.1.100 master.gamespy.com
+        192.168.1.100 motd.gamespy.com
+        192.168.1.100 gpsp.gamespy.com
+        192.168.1.100 gpcm.gamespy.com
+        192.168.1.100 gamespy.com
+        192.168.1.100 bf2web.gamespy.com
+        192.168.1.100 gamestats.gamespy.com
+        192.168.1.100 eapusher.dice.se
+    networks:
+      - bf2-network
+    depends_on:
+      test-ready:
+        condition: service_completed_successfully
+    stop_signal: SIGKILL
+    entrypoint:
+      - /bin/sh
+    command:
+      - -c
+      - |
+          set -eu
+          echo "$$DNS" | awk NF | while read -r ip h; do
+              if nslookup $$h coredns | grep -E "^Address: $$ip" > /dev/null; then
+                  echo "PASS: $$h"
+              else
+                  echo "FAIL: $$h"
+                  exit 1
+              fi
+          done
+
 networks:
   bf2-network:
-    name: bf2-network
